### ISSUE TITLE
Bolt-On(Membership) - Feasibility of membership Bolt-On

### ISSUE THREAD

**Issue by jdtg7** [bristol-rowing/backlog#52]
Investigating how the idea for an op-in membership fee would be rolled out on the website without making normal treasury admin more difficult. That money then used for a 'hardship fund' accessed by members via fundraising officer and squad captains. 

Options for £1, £5, £10 or a custom amount. Similar to how events are currently added? but on a rolling subscription. Ability to cancel or change level of commitment. Ability for committee to bulk contact those who donate to say thanks and show where the money has gone. 

Alternatives considered was using normal bank transfers or a separate crowd-sourcing like system/page. Lose a percentage to admin and more complex oversight for stretched treasury team. 

**Additional context**
New to Committee and website function. Happy to discuss more if you need.

**Comment by jdtg7** [comment]
Additional GDPR issue of people seeing where another user has had the account credited from hardship fund?

**Comment by ct5845** [comment]
Hmm yer so we have the following "bolt-ons" added per the treasurers request;
![image](https://github.com/bristol-rowing/backlog/assets/2804348/cccd9b87-612e-43af-a6a7-fd76f103d35e)

I'm not sure anyone is on them. & I guess the issue is they simply get added to a user subs, whilst I believe what you're after is far more of a dedicated "Hardship fund", there's also no custom amount, and it's only membership and treasurer that can affect this.

So if I've got this right;
 
- [ ] A method for users to contribute on a monthly basis? £x amount, which goes into a "Hardship fund". Presumably this get's taken out of their account at the same time as subs.
- [ ] A "hardship fund manager"/role, separate to the treasurer role,  and page/functionality where the manager can transfer £y amount to other users. 
- [ ] Security/Privacy where only admins can view movement of money in peoples accounts, so it'll only be admins + the recipient who would/should see monies going in/out. (Everyone get's an overview so could see total in / out but not personal).

**Comment by jdtg7** [comment]
I had no idea the club fund options already existed. I will chat with Jenny who currently 'owns' the project to see what she thinks. 

Otherwise, yes I think your points are correct. If the treasury team is happy to take on the fund management that would be fine. Fund. and Caps. don't need the functionality itself to allocate monies via website and would instead agree to where/who it can go towards. If you think they are the better people to have that sort of permission then I am happy for that to go forwards.
